import Head from 'next/head'
import Link from 'next/link'
import Layout from '../components/layout'
import Plant from '../components/plant'
import styles from '../styles/Home.module.css'
import { getPlantsData } from '../lib/plants'


export async function getStaticProps() {
  const allPlantsData = await getPlantsData()
  return {
    props: { allPlantsData }
  }
}

export default function Home({allPlantsData}) {
  return (
    <Layout>
      <div className={styles.container}>
        <Head>
          <title>Plant Tracker</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <div>
            <h3 className={styles.title}>
              Plant Tracker
            </h3>
          </div>
          <div className="grid grid-cols-4 gap-4">
              {allPlantsData.map(({id, plant_name, watering_instruction, species: {species_name}, created_at, image}) => (
                  <li className="list-none" key={id}>
                    <Plant id={id} plant_name={plant_name} watering_instruction={watering_instruction} species_name={species_name} created_at={created_at} image={image} />
                  </li>
              ))}
          </div>

          <div className='fixed bottom-0 w-full'>
            <button className='my-8 float-right px-5 py-2 bg-green-500 text-white text-sm font-bold tracking-wide rounded-full focus:shadow-outline' type="button">
              <Link href="/plants/add-plant">
                <a>Add A Plant</a>
              </Link>
            </button>
          </div>
          
        </main>

      </div>
    </Layout>
  )  
}
